set test "stub-resolver"

set expected_calls {
    "call @foo with"
    "call @bar@5b2 with"
}

set not_expected "call @bar with"

set file "dyn/x86_64-elf_so"
exec bap "$file" --read-symbols-from "data/x86_64-elf_so.symbols" "--dump=bir:$file.out"

foreach call $expected_calls {
    non-zero-matches $file $call "$test for $call"
}

zero-matches $file $not_expected "$test for $not_expected"
exec rm -f "$file.out"
