set test "propagate taint"
set regs {ZF}
set bir_attrs {tainted-reg tainted-regs visited}

set opts "-d --propagate-taint"
foreach reg $regs {lappend opts "--taint-reg=$reg"}
foreach attr $bir_attrs {lappend opts "--print-bir-attr=$attr"}

proc run-again {file attr} {
    global opts
    global test
    set command "bap $opts -- $file"
    uplevel 1 spawn $command
    expect {
        ".$attr" {pass "AGAIN PASS $test $attr in $file"}
        default {fail "AGAIN FAIL $test $attr in $file"}
    }
}


foreach attr $bir_attrs {
    foreach-binary {file *} "bap $opts" {
        ".$attr" {
            pass "$test $attr in $file"
        }
        default  {
            run-again $file $attr
            fail "$test $attr in $file"
        }
    }
}
