set test "propagate taint"
set regs {ZF}
set bir_attrs {tainted-reg tainted-regs visited}

set opts "-d --propagate-taint"
foreach reg $regs {lappend opts "--taint-reg=$reg"}
foreach attr $bir_attrs {lappend opts "--print-bir-attr=$attr"}

proc run-again {file attr} {
    global opts
    global test
    puts "start to run again to test $attr in $file"
    set command "bap $opts -- $file"
    uplevel 1 spawn $command
    expect {
        ".$attr" {pass "AGAIN PASS $test $attr in $file"}
        default {fail "AGAIN FAIL $test $attr in $file"}
    }
}


foreach attr $bir_attrs {
    set a "false"
    set f_file ""
    set f_attr ""

    foreach-binary {file *} "bap $opts" {
        ".$attr" {
            pass "$test $attr in $file"
        }
        default  {
            set a "true"
            set f_file $file
            set f_attr $attr
            fail "$test $attr in $file"
        }
    }
    if {[string compare $a "true"] == 0} {
        run-again $f_file $f_attr
    }
}
