language: c
sudo: false
script: bash -ex .run_travis.sh
cache:
  directories:
    - $HOME/.opam
  before_cache:
    - opam remove bap -y
    - opam remove bap-veri -y
    - rm -rf $HOME/.opam/log
    - rm -rf $HOME/.local/state/bap
addons:
  apt:
    sources:
    - avsm
    packages:
    - camlp4
    - camlp4-extra
    - clang
    - curl
    - libcurl4-gnutls-dev
    - libgmp-dev
    - libssl-dev
    - libzip-dev
    - llvm
    - llvm-3.8-dev
    - m4
    - ocaml
    - ocaml-base
    - ocaml-base-nox
    - ocaml-compiler-libs
    - ocaml-native-compilers
    - ocaml-nox
    - time
    - aspcud
    - dejagnu

env:
  global:
  - FORK_USER=talex5 FORK_BRANCH=containers OPAMYES=true OCAML_VERSION=4.05.0 OPAM_INIT=true OPAM_SWITCH=$OCAML_VERSION TESTS=false
  matrix:
  - BAP_RUN_CHECK=true BAP_RUN_MC=false BAP_RUN_PRIMUS=false  BAP_RUN_VERI=false
  - BAP_RUN_CHECK=false BAP_RUN_MC=true BAP_RUN_PRIMUS=false  BAP_RUN_VERI=false
  - BAP_RUN_CHECK=false BAP_RUN_MC=false BAP_RUN_PRIMUS=true  BAP_RUN_VERI=false
  - BAP_RUN_CHECK=false BAP_RUN_MC=false BAP_RUN_PRIMUS=false  BAP_RUN_VERI=true